#! /usr/bin/env zsh

if [[ -z ${DOTFILES} ]] ; then
	DOTFILES=$(dirname "$0")
fi

if [[ ! -d ${DOTFILES} ]] ; then
	echo "Directory '${DOTFILES}' does not exist" 1>&2
	return 1
fi

integer retcode=0
cd "${DOTFILES}"
DOTFILES=$(pwd)
for filename in * ; do
	if [[ ${filename:0:4} = dot. ]] ; then
		target=${filename:3}
		target="${HOME}/${target//--/\/}"

		if [[ -L ${target} ]] ; then
			existing_target=$(readlink -f "${target}")
			if [[ ${DOTFILES}/${filename} != ${existing_target} ]] ; then
				echo "Symlink '${target}' points to '${existing_target}' instead of '${DOTFILES}/${filename}'" 1>&2
				retcode=2
			fi
			continue
		fi

		if [[ -r ${target} ]] ; then
			echo "Warning: '${target}' is not a symlink" 1>&2
			retcode=1
			continue
		fi

		ln -s "${DOTFILES}/${filename}" "${target}"
	fi
done
exit ${retcode}
