#! /bin/sh

for f in Xdefaults Xresources ; do
	if test -r ~/.$f ; then
		xrdb -merge ~/.$f
	elif test -r ~/.dotfiles/$f ; then
		xrdb -merge ~/.dotfiles/$f
	fi
done

export DMENU_OPTIONS='-fn terminus:bold:size=15 -h 20 -x 0'

setxkbmap -layout es -option 'ctrl:nocaps,compose:menu'
xsetroot -solid steelblue
